title: Stackbit Vanilla Theme
baseurl: /
permalink: '/:title/'
collections:
  posts:
    permalink: '/posts/:title/'
description: A vanilla theme for Stackbit
header:
  title: ''
  has_nav: true
  nav_links:
    - label: Home
      url: /
    - label: Projects
      url: /projects
      new_window: false
      no_follow: false
      type: action
    - label: Contact
      url: /elements/
footer:
  content: ''
  has_social: false
  social_links:
    - label: Twitter
      url: 'https://twitter.com/'
      new_window: true
    - label: Instagram
      url: 'https://www.instagram.com/'
      new_window: true
    - label: GitHub
      url: 'https://github.com/'
      new_window: true
    - label: LinkedIn
      url: 'https://www.linkedin.com/'
      new_window: true
    - label: DEV
      url: 'https://dev.to/'
      new_window: true
  links: []
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
