title: Homepage
baseurl: /
permalink: '/:title/'
collections:
  posts:
    permalink: '/posts/:title/'
description: Homepage of Ruslan Novikov
header:
  title: ''
  has_nav: true
  nav_links:
    - label: Home
      url: /
    - label: Portfolio
      url: /projects
      new_window: false
      no_follow: false
      type: action
    - label: Contact
      url: /elements/
footer:
  content: 'This homepage has been created with Stackbit. Social media links:'
  has_social: true
  social_links:
    - label: GitHub
      url: 'https://github.com/Ruslando'
      new_window: true
    - label: LinkedIn
      url: 'https://www.linkedin.com/in/ruslannov/'
      new_window: true
    - label: Jovian
      url: 'https://jovian.ai/ruslando'
      new_window: false
      no_follow: false
      type: action
  links: []
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
